<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="Sensor" Id="{d0d68e7f-7704-44bc-9f8a-72c692921bab}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Sensor
VAR
	sensorA	: OMH555_Decoder;
	sensorB : OMH555_Decoder;
	sensorC : OMH555_Decoder;
	sensorD : OMH555_Decoder;
	
	sensor_test_pos : LREAL;

END_VAR

VAR_INPUT
	Set_SensoeZero: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// 測距感應器
sensorA();
sensorB();
sensorc();
sensorD();



]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>